### ISSUE TITLE
Remove 3.6 Support

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#267]
Python 3.6 has been deemed End of Life (EOL) since December 2021. 

We should make moves to stop supporting it.

# Tasks
- [ ] Remove 3.6 test support.
- [ ] Remove 3.6 specific code.
- [ ] Update `setup.py` to not list 3.6 and set minimum python version to 3.7.
- [ ] Update any documentation & markdown files to remove reference to 3.6. 
- [ ] Create pull request with all the changes.
- [ ] Determine timeline for a merge. With telemetry -- we should be able to confirm whether anyone is using Hamilton with python 3.6. If so then it should be easy to remove, if not, we'll then need to understand what's stopping people from moving to 3.7+. (See @skrawcz to know whether this is the case or not).

**Comment by skrawcz** [comment]
@MDK8888 sure want to give it a try and come up with a pull request? Hopefully the task list gives you a good idea of what to do/search for.

**Comment by skrawcz** [comment]
@MDK8888 do you have an ETA on this? We'd like to get this out in February, so let me know if that fits your timeline, otherwise I can reassign this issue. Thanks.

**Comment by elijahbenizzy** [comment]
Hey @MDK8888 -- ended up working on this. It was super quick and not that interesting :) Think you can find an equivalently easy yet more interesting first issue :)

**Comment by skrawcz** [comment]
#291 removed 3.6
